name: "Rubocop Run Action"
description: "Runs Rubocop linter with given config"
author: "d-lebed"
branding:
  icon: "check-circle"
  color: "black"

inputs:
  options:
    description: "Rubocop command line options"
  preserve_exitcode:
    description: "Preserve rubocop exit code"
    type: "boolean"
    default: true

runs:
  using: "docker"
  image: "docker://ghcr.io/d-lebed/rubocop-run-action:pr-2"
  args:
    - ${{ inputs.options }}
