name: "RuboCop Run Action"

description: "Runs RuboCop linter with given config"
author: "d-lebed"
branding:
  icon: "check-circle"
  color: "black"

inputs:
  options:
    description: "RuboCop command line options"
    default: "--format=github"
  preserve_exitcode:
    description: "Preserve RuboCop exit code"
    type: "boolean"
    default: true
  workdir:
    description: "From which directory to run RuboCop"

runs:
  using: "docker"
  image: "docker://ghcr.io/d-lebed/rubocop-run-action:0.3.0"
  args:
    - ${{ inputs.options }}
