name: "Rubocop Run Action"
description: "Runs Rubocop linter with given config"
author: "d-lebed"
branding:
  icon: "check-circle"
  color: "black"

inputs:
  options:
    description: "Rubocop command line options"
  preserve_exitcode:
    description: "Preserve rubocop exit code"
    type: "boolean"
    default: false
  test_string:
    description: "Test string"
  test_first:
    description: "Test first boolean"
    type: "boolean"
  test_other:
    description: "Test other boolean"
    type: "boolean"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.options }}
