services:
  dev:
    build:
      context: .
      dockerfile: .dockerdev/Dockerfile
    volumes:
      - bundle:/usr/local/bundle
      - .:/rubocop

  action:
    build:
      context: .

volumes:
  bundle:
