#!/usr/bin/env sh

RUNNER_WORKDIR=${INPUT_WORKDIR:-.}
RUNNER_OPTIONS=${INPUT_OPTIONS:-"$@"}
RUNNER_EXTRA_OPTIONS=""

if $INPUT_RDJSON_FORMATTER; then
  RUNNER_EXTRA_OPTIONS="${RUNNER_EXTRA_OPTIONS} --require /rubocop/lib/rdjson_formatter.rb"
fi

if [[ -z ${GITHUB_WORKSPACE} ]]; then
  cd ${RUNNER_WORKDIR}
else
  cd ${GITHUB_WORKSPACE}/${RUNNER_WORKDIR}
fi

bundle exec rubocop ${RUNNER_EXTRA_OPTIONS} ${RUNNER_OPTIONS}
EXITCODE=$?

if $INPUT_PRESERVE_EXITCODE; then
  exit $EXITCODE
fi
